### ISSUE TITLE
CWD not supported for replays

### ISSUE THREAD

**Issue by NikEyX** [chippydip/go-sc2ai#10]
This works for me:
```
        cwd, _ := os.Getwd()
        replayPath := filepath.Join(cwd, "data/replays/test.SC2Replay")
```
and this won't:
```
        replayPath := "data/replays/test.SC2Replay"
```
I presume that somewhere in the replay opening code, it uses cwd, _ := os.Executable() or something like that to get the current working directory, but if you use symlinks, etc, then using os.Executable() gives you the "wrong" path. For the same reason it also fails when we direct it at the folder as such: 
```
        replayPath := "data/replays/
```

Absolute paths work.

**Comment by chippydip** [comment]
Should be an easy fix
